add sequence extraction for principled handling of perf info and user messages

diff --git a/.ci/scripts/check_gibberish b/.ci/scripts/check_gibberish
--- a/.ci/scripts/check_gibberish
+++ b/.ci/scripts/check_gibberish
@@ -3,8 +3,16 @@
 #!/bin/bash
 # Check the spelling of the specified file
 cat "$1"
-# We exclude some messages generated by the code because device names, file names, or JIT, DSO, PTE are not necessarily English words
-cat "$1" | grep -v "Using device" | grep -v "JIT compilation time" | grep -v "Warning" | aspell -a -c  | grep '^[\&#]' >/tmp/out.$$
+# We extract only the sequence output and don't spell check status and performance stats
+TMPFILE=/tmp/`basename "$1"`-sequence
+python3 .ci/scripts/extract-sequence.py "$1" >$TMPFILE
+
+if [ $? -ne 0 ]; then
+    echo "Sequence extraction failed. Exiting."
+    exit 1
+fi
+
+cat ${TMPFILE} |  aspell -a -c  | grep '^[\&#]' >/tmp/out.$$
 # Exit with a non-zero status code if there were any spelling errors because:
 # * Finding one or more lines with & or # means we found a spelling error, might be gibberish
 if [ $? -ne 0 ]; then
