move gguf tests to script (#771)

diff --git a/.ci/scripts/run-docs b/.ci/scripts/run-docs
--- a/.ci/scripts/run-docs
+++ b/.ci/scripts/run-docs
@@ -40,3 +40,19 @@ if [ "$1" == "quantization" ]; then
 
         exit 0
 fi
+
+if [ "$1" == "gguf" ]; then
+        echo "::group::Create script to run gguf"
+        python3 scripts/updown.py --file docs/GGUF.md --replace 'llama3:stories15M,-l 3:-l 2,meta-llama/Meta-Llama-3-8B-Instruct:stories15M' --suppress huggingface-cli,HF_TOKEN > ./run-gguf.sh
+        # for good measure, if something happened to updown processor,
+        # and it did not error out, fail with an exit 1
+        echo "exit 1" >> ./run-gguf.sh
+        echo "::endgroup::"
+
+        echo "::group::Run gguf"
+        echo "*******************************************"
+        cat ./run-gguf.sh
+        echo "*******************************************"
+        bash -x ./run-gguf.sh
+        echo "::endgroup::"
+fi
