Update run-docs
Add back command explaining seemingly extraneous `echo exit 1`

diff --git a/.ci/scripts/run-docs b/.ci/scripts/run-docs
--- a/.ci/scripts/run-docs
+++ b/.ci/scripts/run-docs
@@ -49,6 +49,7 @@ esac
 # Generate the script
 echo "::group::Create script to run $1"
 python3 torchchat/utils/scripts/updown.py --file "$filepath" $parameters > "$script_name"
+# if something happened to updown processor, and it did not error out, fail with an exit 1
 echo "exit 1" >> "$script_name"
 echo "::endgroup::"
 
