make it twice as nice

diff --git a/.github/workflows/run-readme-periodic.yml b/.github/workflows/run-readme-periodic.yml
--- a/.github/workflows/run-readme-periodic.yml
+++ b/.github/workflows/run-readme-periodic.yml
@@ -36,6 +36,9 @@ jobs:
 
         echo "::group::Create script"
         python3 scripts/updown.py --file README.md > ./we-run-this.sh
+        # for good measure, if something happened to updown processor,
+        # and it did not error out, fail with an exit 1
+        echo "exit 1" >> ./we-run-this.sh
         echo "::endgroup::"
 
         echo "::group::Run This"
diff --git a/.github/workflows/run-readme-pr.yml b/.github/workflows/run-readme-pr.yml
--- a/.github/workflows/run-readme-pr.yml
+++ b/.github/workflows/run-readme-pr.yml
@@ -27,6 +27,9 @@ jobs:
 
         echo "::group::Create script"
         python3 scripts/updown.py --file README.md --replace llama3:stories15M --suppress huggingface-cli,HF_TOKEN > ./we-run-this.sh
+        # for good measure, if something happened to updown processor,
+        # and it did not error out, fail with an exit 1
+        echo "exit 1" >> ./we-run-this.sh
         echo "::endgroup::"
 
         echo "::group::Run This"
