Updown (#682)
* improve updown parser, and use in README.md execution

* cut/paste errors

* typo: true -> false

* we scan each partial line, so need to suppress at partial line level :(

* make it twice as nice

diff --git a/.github/workflows/run-readme-pr.yml b/.github/workflows/run-readme-pr.yml
--- a/.github/workflows/run-readme-pr.yml
+++ b/.github/workflows/run-readme-pr.yml
@@ -26,13 +26,13 @@ jobs:
         # echo "::endgroup::"
 
         echo "::group::Create script"
-        echo "set -eou pipefail" > ./readme-commands.sh
-        python3 scripts/process-readme.py >> ./readme-commands.sh
-        echo "exit 1" >> ./readme-commands.sh
+        python3 scripts/updown.py --file README.md --replace llama3:stories15M --suppress huggingface-cli,HF_TOKEN > ./we-run-this.sh
+        # for good measure, if something happened to updown processor,
+        # and it did not error out, fail with an exit 1
+        echo "exit 1" >> ./we-run-this.sh
         echo "::endgroup::"
 
         echo "::group::Run This"
-        grep -v login ./readme-commands.sh | sed  -e '1,$s/llama3/stories15M/g' > ./we-run-this.sh
         echo "*******************************************"
         cat ./we-run-this.sh
         echo "*******************************************"
