Run quantization.md document from docs/ (#718)
* improve updown parser, and use in README.md execution

* cut/paste errors

* typo: true -> false

* we scan each partial line, so need to suppress at partial line level :(

* make it twice as nice

* improved updown parsing

* special handling for lines w/o option

* enable run on quantization doc

* handle white space before trip backtick

* updates

* mps test

* updates

* Update run-readme-pr-macos.yml

Rename test to avoid babe conflict

* Update run-readme-pr.yml

Y

* Update run-readme-pr-mps.yml

2

* typos

* add updown end command

* typo

* move broken mps

* Update parking_lot/run-readme-pr-mps.yml

Co-authored-by: Eli Uriegas <1700823+seemethere@users.noreply.github.com>

---------

Co-authored-by: Eli Uriegas <1700823+seemethere@users.noreply.github.com>

diff --git a/.github/workflows/run-readme-pr.yml b/.github/workflows/run-readme-pr.yml
--- a/.github/workflows/run-readme-pr.yml
+++ b/.github/workflows/run-readme-pr.yml
@@ -25,19 +25,57 @@ jobs:
         # export PATH=/opt/rh/devtoolset-10/root/usr/bin/:$PATH
         # echo "::endgroup::"
 
-        echo "::group::Create script"
-        python3 scripts/updown.py --file README.md --replace 'llama3:stories15M,-l 3:-l 2,meta-llama/Meta-Llama-3-8B-Instruct:stories15M' --suppress huggingface-cli,HF_TOKEN > ./we-run-this.sh
+        echo "::group::Create script to run README"
+        python3 scripts/updown.py --file README.md --replace 'llama3:stories15M,-l 3:-l 2,meta-llama/Meta-Llama-3-8B-Instruct:stories15M' --suppress huggingface-cli,HF_TOKEN > ./run-readme.sh
         # for good measure, if something happened to updown processor,
         # and it did not error out, fail with an exit 1
-        echo "exit 1" >> ./we-run-this.sh
+        echo "exit 1" >> ./run-readme.sh
         echo "::endgroup::"
 
-        echo "::group::Run This"
+        echo "::group::Run README"
         echo "*******************************************"
-        cat ./we-run-this.sh
+        cat ./run-readme.sh
         echo "*******************************************"
-        bash -x ./we-run-this.sh
+        bash -x ./run-readme.sh
+        echo "::endgroup::"
 
+        echo "::group::Completion"
+        echo "tests complete"
+        echo "*******************************************"
+        echo "::endgroup::"
+
+  test-quantization-any:
+    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
+    with:
+      runner: linux.g5.4xlarge.nvidia.gpu
+      gpu-arch-type: cuda
+      gpu-arch-version: "12.1"
+      timeout: 60
+      script: |
+        echo "::group::Print machine info"
+        uname -a
+        echo "::endgroup::"
+
+        # echo "::group::Install newer objcopy that supports --set-section-alignment"
+        # yum install -y  devtoolset-10-binutils
+        # export PATH=/opt/rh/devtoolset-10/root/usr/bin/:$PATH
+        # echo "::endgroup::"
+
+        echo "::group::Create script to run quantization"
+        python3 scripts/updown.py --file docs/quantization.md --replace llama3:stories15M --suppress huggingface-cli,HF_TOKEN > ./run-quantization.sh
+        # for good measure, if something happened to updown processor,
+        # and it did not error out, fail with an exit 1
+        echo "exit 1" >> ./run-quantization.sh
+        echo "::endgroup::"
+
+        echo "::group::Run quantization"
+        echo "*******************************************"
+        cat ./run-quantization.sh
+        echo "*******************************************"
+        bash -x ./run-quantization.sh
+        echo "::endgroup::"
+
+        echo "::group::Completion"
         echo "tests complete"
         echo "*******************************************"
         echo "::endgroup::"
