Updown (#682)
* improve updown parser, and use in README.md execution

* cut/paste errors

* typo: true -> false

* we scan each partial line, so need to suppress at partial line level :(

* make it twice as nice

diff --git a/.github/workflows/run-readme-periodic.yml b/.github/workflows/run-readme-periodic.yml
--- a/.github/workflows/run-readme-periodic.yml
+++ b/.github/workflows/run-readme-periodic.yml
@@ -35,14 +35,19 @@ jobs:
         # echo "::endgroup::"
 
         echo "::group::Create script"
-        echo "set -eou pipefail" > ./we-run-this.sh
-        python3 scripts/process-readme.py >> ./we-run-this.sh
-        echo "exit 1"  >> ./we-run-this.sh
+        python3 scripts/updown.py --file README.md > ./we-run-this.sh
+        # for good measure, if something happened to updown processor,
+        # and it did not error out, fail with an exit 1
+        echo "exit 1" >> ./we-run-this.sh
         echo "::endgroup::"
 
         echo "::group::Run This"
+        echo "*******************************************"
+        cat ./we-run-this.sh
+        echo "*******************************************"
         bash -x ./we-run-this.sh
         
         echo "tests complete"
-        echo "******************************************"
+        echo "*******************************************"
         echo "::endgroup::"
+
